name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/victorlpgazolli/gh-mount:latest
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "./scripts/build.sh"
  # release-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build for Intel macOS
  #       run: bash ./scripts/build.sh
  #       env:
  #         TARGET_TRIPLE: x86_64-apple-darwin
  #         GOOS_GOARCH: darwin-amd64
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: aarch64-apple-darwin
  #     - name: Build for Apple Silicon macOS
  #       run: bash ./scripts/build.sh
  #       env:
  #         TARGET_TRIPLE: aarch64-apple-darwin
  #         GOOS_GOARCH: darwin-arm64
  #     - name: Upload release artifact
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         draft: false
  #         prerelease: false
  #         files: |
  #           dist/darwin-amd64
  #           dist/darwin-arm64
  # release-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build for x86_64 Windows
  #       run: bash ./scripts/build.sh
  #       env:
  #         TARGET_TRIPLE: x86_64-pc-windows-msvc
  #         GOOS_GOARCH: windows-amd64.exe
  #     - name: Upload release artifact
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         draft: false
  #         prerelease: false
  #         files: |
  #           dist/windows-amd64.exe